#!/command/with-contenv sh

#IP=$( hostname -I )
IP=$( hostname -I | awk '{print $1}' )
#IP=$( ip a | grep inet | grep "eth0\|en" | awk '{print $2}' | tr '/' ' ' | awk '{print $1}' )

exec /ambed/ambed ${IP}
