version: '3.8'

networks:
  proxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"
          ip_range: "10.0.0.0/24"

services:
  ambed:
    image: mfiscus/ambed:latest
    container_name: ambed
    hostname: ambed_container
    networks:
      - proxy
    privileged: true # Necessary for accessing AMBE usb dongle(s)
    restart: unless-stopped